// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

type Query struct {
}

type Shipments struct {
	ID            string `json:"id"`
	OrderID       string `json:"order_id"`
	UserCarrierID string `json:"user_carrier_id"`
	Status        string `json:"status"`
	CreatedAt     string `json:"created_at"`
	UpdatedAt     string `json:"updated_at"`
}
