// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph


type Query struct {
}

type Shipment struct {
	
	ShipmentID    string `json:"shipmentID"`
	OrderID       int    `json:"orderID"`
	CarrierID     int    `json:"carrierID"`
	State         string `json:"state"`
	DateAsignment string `json:"dateAsignment"`
}

func (Shipment) TableName() string {
    return "shipment"
}





